function determManufacturer(art) {
    let manArr = {
        Akkord: 90,
        Aldit: '',
        Alfa: 34,
        Ambiente: '',
        Artelamp: 4,
        Artglass: 40,
        'Arti Lampadari': 93,
        Bogates: 69,
        'Bohemia Ivele Crystal': 96,
        Brilliant: 80,
        Brizzi: 6,
        Bydzov: 44,
        Chiaro: 50,
        Citilux: 16,
        Collezioni: 81,
        Colosseo: 23,
        'Crystal Lamp': 82,
        'Crystal Lux': 100,
        DeMarkt: 64,
        'Dio D\'Arte': 113,
        Divinare: 83,
        Dream: 77,
        Dreamfan: 108,
        Eglo: 10,
        Elektrostandard: 76,
        Eletto: 71,
        'Elite Bohemia': 8,
        Emoi: '',
        Faro: 73,
        Favourite: 37,
        Feron: 79,
        Freya: 104,
        Glasslps: 63,
        Globo: 15,
        'Ideal Lux': 111,
        Idlamp: 78,
        Kronem: '',
        Lightstar: 22,
        'Lis lighting': 0,
        'Loft IT': 105,
        Luminex: 52,
        Lumion: 99,
        Lussole: 3,
        Mantra: 1,
        Markslojd: 39,
        Maytoni: 20,
        'Moritz Zdekauer': '',
        'MW-Light': 35,
        Namat: 72,
        'Natali Kovaltseva': 75,
        Newport: 112,
        NLight: 74,
        Novotech: 12,
        Nowodvorski: 66,
        Odeon: 2,
        Omnilux: 102,
        Osgona: '',
        Powerlight: 114,
        Preciosa: 43,
        'Reccagni Angelo': 24,
        'Regenbogen Life': '',
        'Rolling Stars': 28,
        'Royal Bohemian': 97,
        Sigma: 26,
        'Silver Light': 87,
        Selecta: 21,
        'Селекта': 21,
        Smartbuy: 106,
        Sonex: 19,
        'St Luce': 47,
        Svetresurs: 9,
        'TK Lighting': 65,
        Toplight: 103,
        Toscom: 88,
        Velante: 101,
        Vitaluce: 98,
        Westinghouse: '',
        Wranovsky: 46,
        'Zaklad Stolarski': 67,
        'Авангард': 22,
        'Аврора': 92,
        'Альфа': 34,
        'Артгласс': 40,
        'Артеламп': 4,
        'Бриллиант': 80,
        'Глобо': 15,
        'Дримфан': 108,
        'Дубравия': 89,
        'Евросвет': 5,
        'Лайтстар': 22,
        'Майтони': 20,
        'Максисвет': 107,
        'Мантра': 1,
        'Новотек': 12,
        'Одеон': 2,
        'Омнилюкс': 102,
        'Светресурс': 9,
        'Ситилюкс': 16,
        'Сонекс': 19,
        'Фаворит': 37,
        'Фаро': 73,
        'Ферон': 79,
        'Электростандарт': 76
    }

    let result = '';
    for (let key in manArr) {
        if (art.indexOf(key) !== -1) {
            result = manArr[key];
            break;
        }
    }

    return result;     
}
        
console.log(determManufacturer('Бра Powerlight MIOMI 1111/1W-1RED'));